server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
#      url: "jdbc:mysql://localhost:3306/InventoryManagement"
#      username: root
#      password: root
    url: jdbc:mysql://swd392-mysql-server.mysql.database.azure.com:3306/InventoryManagement?useSSL=true&requireSSL=false&enabledTLSProtocols=TLSv1.2
    username: duongtb
    password: 17122004Admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080/api
    title: API Service
    version: 1.0.0
jwt:
  signerKey: "eaRge+NAiFb7HQITA/QcCaDmS7QXJlwy7UpOAJj5/ddqoWCYQquoPXkget8OK+zA"
