name: Build and deploy JAR app to Azure Web App - clothingcompany

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Bước checkout mã nguồn từ repo
      - uses: actions/checkout@v4

      # Kiểm tra thư mục hiện tại và liệt kê file
      - name: Check current directory
        run: echo "Current directory: ${{ github.workspace }}" && dir "${{ github.workspace }}"

      # Kiểm tra xem file pom.xml có tồn tại không
      - name: Check if pom.xml exists
        run: |
          if (Test-Path "${{ github.workspace }}/SWD392_Warehouse_management/BE_Mobile/app/pom.xml") {
            echo "pom.xml found"
          } else {
            echo "pom.xml NOT found"
            exit 1
          }

      # Cài đặt Java
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      # Build project với Maven
      - name: Build with Maven
        run: mvn -f "${{ github.workspace }}/SWD392_Warehouse_management/BE_Mobile/app/pom.xml" clean install

      # Upload file JAR để deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "${{ github.workspace }}/SWD392_Warehouse_management/BE_Mobile/app/target/*.jar"

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      # Tải file JAR từ bước build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Đăng nhập Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy lên Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'clothingcompany'
          slot-name: 'Production'
          package: '*.jar'
